/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import CapaDTO.Cliente;
import CapaDTO.Repartidor;
import CapaNegocio.NegocioRepartidor;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xTheBlackKeYx
 */
public class PantallaRepartidor extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRepartidor
     */
    public PantallaRepartidor() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdRepartidor.setVisible(false);
        this.ListarRepartidor();
    }
    
    Repartidor repartidor = new Repartidor();
    NegocioRepartidor  nr = new NegocioRepartidor();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public void ListarRepartidor(){
        modelo = (DefaultTableModel) this.tableListarRepartidor.getModel();
        
        modelo.setNumRows(0);
        int fila =0;
        
        Iterator iter = nr.ListarRepartidor().iterator();
        while(iter.hasNext()){
            repartidor = (Repartidor) iter.next();
            Object[] num ={};
            modelo.addRow(num);
            this.tableListarRepartidor.setValueAt(repartidor.getIdRepartidor(), fila, 0);
            this.tableListarRepartidor.setValueAt(repartidor.getRutRepartidor(), fila, 1);
            this.tableListarRepartidor.setValueAt(repartidor.getNombreRepartidor(), fila, 2);
            this.tableListarRepartidor.setValueAt(repartidor.getDireccion(), fila, 3);
            this.tableListarRepartidor.setValueAt(repartidor.getTelefono(), fila, 4);
            fila++;
        }
    }
    
    
    private void LimpiarRepartidor(){
        txtIdRepartidor.setText("");
        txtRutRepartidor.setText("");
        txtNombreRepartidor.setText("");
        txtTelefonoRepartidor.setText("");
        txtDireccionRepartidor.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRutRepartidor = new javax.swing.JTextField();
        txtNombreRepartidor = new javax.swing.JTextField();
        txtDireccionRepartidor = new javax.swing.JTextField();
        txtTelefonoRepartidor = new javax.swing.JTextField();
        btnAgregarRepartidor = new javax.swing.JButton();
        btnModificarRepartidor = new javax.swing.JButton();
        btnEliminarRepartidor = new javax.swing.JButton();
        txtIdRepartidor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListarRepartidor = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVolverRepartidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rut");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Repartidor");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Direccion");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Telefono");

        btnAgregarRepartidor.setText("Agregar");
        btnAgregarRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRepartidorActionPerformed(evt);
            }
        });

        btnModificarRepartidor.setText("Modificar");
        btnModificarRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRepartidorActionPerformed(evt);
            }
        });

        btnEliminarRepartidor.setText("Eliminar");
        btnEliminarRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRepartidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtIdRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtRutRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccionRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnAgregarRepartidor)
                        .addGap(75, 75, 75)
                        .addComponent(btnModificarRepartidor)
                        .addGap(63, 63, 63)
                        .addComponent(btnEliminarRepartidor)))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefonoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRepartidor)
                    .addComponent(btnModificarRepartidor)
                    .addComponent(btnEliminarRepartidor))
                .addContainerGap())
        );

        tableListarRepartidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Rut", "Nombre Repartidor", "Direccion", "Telefono"
            }
        ));
        tableListarRepartidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListarRepartidorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListarRepartidor);

        jLabel5.setText("Buscar Repartidor");

        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setText("NOMBRE DEL USUARIO");

        jLabel7.setText("NUEVO REPARTIDOR");

        btnVolverRepartidor.setText("Volver");
        btnVolverRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRepartidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(681, 681, 681)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addGap(264, 264, 264)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(btnVolverRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRepartidorActionPerformed
        // TODO add your handling code here:
        try{   
            repartidor.setRutRepartidor(txtRutRepartidor.getText());
            repartidor.setNombreRepartidor(txtNombreRepartidor.getText());
            repartidor.setTelefono(Integer.parseInt(txtTelefonoRepartidor.getText()));
            repartidor.setDireccion(txtDireccionRepartidor.getText());
            nr.insertarRepartidor(repartidor);
            LimpiarRepartidor();
            ListarRepartidor();
            JOptionPane.showMessageDialog(null, "Repartidor Agregado");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Repartidor No Agregado" + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarRepartidorActionPerformed

    private void tableListarRepartidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListarRepartidorMouseClicked
        // TODO add your handling code here:
        int fila = tableListarRepartidor.rowAtPoint(evt.getPoint());
        txtIdRepartidor.setText(tableListarRepartidor.getValueAt(fila, 0).toString());
        txtRutRepartidor.setText(tableListarRepartidor.getValueAt(fila, 1).toString());
        txtNombreRepartidor.setText(tableListarRepartidor.getValueAt(fila, 2).toString());
        txtDireccionRepartidor.setText(tableListarRepartidor.getValueAt(fila, 3).toString());
        txtTelefonoRepartidor.setText(tableListarRepartidor.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tableListarRepartidorMouseClicked

    private void btnEliminarRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRepartidorActionPerformed
        if(!"".equals(txtIdRepartidor.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar?");
            if(pregunta == 0){
                int id = Integer.parseInt(txtIdRepartidor.getText());
                nr.eliminarRepartidor(id);
                LimpiarRepartidor();
                ListarRepartidor();
            }
            
        }
        
    }//GEN-LAST:event_btnEliminarRepartidorActionPerformed

    private void btnModificarRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRepartidorActionPerformed
        if ("".equals(txtIdRepartidor.getText())) {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        } else {

            if (!"".equals(txtRutRepartidor.getText()) || !"".equals(txtNombreRepartidor.getText()) ||
                    !"".equals(txtDireccionRepartidor.getText()) || !"".equals(txtTelefonoRepartidor.getText())) 
            {
                
                repartidor.setRutRepartidor(txtRutRepartidor.getText());
                repartidor.setNombreRepartidor(txtNombreRepartidor.getText());
                repartidor.setTelefono(Integer.parseInt(txtTelefonoRepartidor.getText()));
                repartidor.setDireccion(txtDireccionRepartidor.getText());
                repartidor.setIdRepartidor(Integer.parseInt(txtIdRepartidor.getText()));
                nr.actualizarRepartidor(repartidor);
                JOptionPane.showMessageDialog(null, "Repartidor Modificado");
                LimpiarRepartidor();
                ListarRepartidor();
                
            } else {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarRepartidorActionPerformed

    private void btnVolverRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRepartidorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.gc();
    }//GEN-LAST:event_btnVolverRepartidorActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRepartidor;
    private javax.swing.JButton btnEliminarRepartidor;
    private javax.swing.JButton btnModificarRepartidor;
    private javax.swing.JButton btnVolverRepartidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tableListarRepartidor;
    private javax.swing.JTextField txtDireccionRepartidor;
    private javax.swing.JTextField txtIdRepartidor;
    private javax.swing.JTextField txtNombreRepartidor;
    private javax.swing.JTextField txtRutRepartidor;
    private javax.swing.JTextField txtTelefonoRepartidor;
    // End of variables declaration//GEN-END:variables
}
