/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import CapaDTO.Cotizacion;
import CapaNegocio.NegocioCotizacion;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristobal
 */
public class PantallaCotizacion extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCotizacion
     */
    public PantallaCotizacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdCotizacion.setVisible(false);
        ListarCotizacion();
    }
    
    Cotizacion cotizacion = new Cotizacion();
    
    NegocioCotizacion nc = new NegocioCotizacion();
    
    DefaultTableModel modelo = new DefaultTableModel();

        //LIMPIAR USUARIO
    private void LimpiarCotizacion(){
        txtNombreTienda.setText("");
        txtDireccionTienda.setText("");
        txtTelefonoTienda.setText("");
        txtUrlTienda.setText("");
        txtDireccionTienda.setText("");
        txtDistribucionTienda.setText("");
    }
    
    //AGREGAR USUARIO
    public void ListarCotizacion(){
        modelo = (DefaultTableModel) this.tableListarTienda.getModel();

        modelo.setNumRows(0);
        int fila =0;

        Iterator iter = nc.listarCotizacion().iterator();
        while(iter.hasNext()){
            cotizacion = (Cotizacion) iter.next();
            Object[] num ={};
            modelo.addRow(num);
            this.tableListarTienda.setValueAt(cotizacion.getIdCotizacion(), fila, 0);
            this.tableListarTienda.setValueAt(cotizacion.getNombreTienda(), fila, 1);
            this.tableListarTienda.setValueAt(cotizacion.getDireccionTienda(), fila, 2);
            this.tableListarTienda.setValueAt(cotizacion.getTelefonoTienda(), fila, 3);
            this.tableListarTienda.setValueAt(cotizacion.getUrlPagTienda(), fila, 4);
            this.tableListarTienda.setValueAt(cotizacion.getDistribucion(), fila, 5);

            fila++;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreTienda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccionTienda = new javax.swing.JTextField();
        txtTelefonoTienda = new javax.swing.JTextField();
        txtUrlTienda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDistribucionTienda = new javax.swing.JTextField();
        btnAgregarTienda = new javax.swing.JButton();
        btnModificarTienda = new javax.swing.JButton();
        btnEliminarTienda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdCotizacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListarTienda = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre Tienda");

        txtNombreTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTiendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Direccion Tienda");

        jLabel3.setText("Telefono Tienda");

        jLabel4.setText("URL Pagina");

        jLabel5.setText("Distribucion");

        btnAgregarTienda.setText("Agregar");
        btnAgregarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTiendaActionPerformed(evt);
            }
        });

        btnModificarTienda.setText("Modificar");
        btnModificarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTiendaActionPerformed(evt);
            }
        });

        btnEliminarTienda.setText("Eliminar");
        btnEliminarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTiendaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nueva Tienda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(txtIdCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreTienda)
                                    .addComponent(txtDireccionTienda)
                                    .addComponent(txtUrlTienda)
                                    .addComponent(txtDistribucionTienda)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefonoTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregarTienda)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarTienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccionTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrlTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDistribucionTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTienda)
                    .addComponent(btnModificarTienda)
                    .addComponent(btnEliminarTienda))
                .addGap(42, 42, 42))
        );

        tableListarTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cotizacion", "Nombre Tienda", "Direccion Tienda", "Telefono Tienda", "Url Pagina", "Distribucion"
            }
        ));
        tableListarTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListarTiendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListarTienda);

        jLabel7.setText("NOMBRE DEL USUARIO");

        jLabel8.setText("Buscar por distribucion");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(225, 225, 225)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTiendaActionPerformed
        //AGREGAR PROVEEDOR
        try{
            cotizacion.setNombreTienda(txtNombreTienda.getText());
            cotizacion.setDireccionTienda(txtDireccionTienda.getText());
            cotizacion.setTelefonoTienda(Integer.parseInt(txtTelefonoTienda.getText()));
            cotizacion.setUrlPagTienda(txtUrlTienda.getText());
            cotizacion.setDistribucion(txtDistribucionTienda.getText());
            nc.insertarCotizacion(cotizacion);
            LimpiarCotizacion();
            ListarCotizacion();
            JOptionPane.showMessageDialog(null, "Cotizacion Agregada");

            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error al agregar Cotizacion" + ex.getMessage());
            
        }
    }//GEN-LAST:event_btnAgregarTiendaActionPerformed

    private void btnModificarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTiendaActionPerformed
        if("".equals(txtIdCotizacion.getText())){
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }else{
            if(!"".equals(txtNombreTienda.getText()) || !"".equals(txtDireccionTienda.getText()) ||
                    !"".equals(txtTelefonoTienda.getText()) || !"".equals(txtUrlTienda.getText()) ||
                    !"".equals(txtDistribucionTienda.getText())){
                cotizacion.setNombreTienda(txtNombreTienda.getText());
                cotizacion.setDireccionTienda(txtDireccionTienda.getText());
                cotizacion.setTelefonoTienda(Integer.parseInt(txtTelefonoTienda.getText()));
                cotizacion.setUrlPagTienda(txtUrlTienda.getText());
                cotizacion.setDistribucion(txtDistribucionTienda.getText());
                nc.actualizarCotizacion(cotizacion);
                JOptionPane.showMessageDialog(null, "Cotizacion Modificada");
                LimpiarCotizacion();
                ListarCotizacion();
                
            }else{
               JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btnModificarTiendaActionPerformed

    private void tableListarTiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListarTiendaMouseClicked
        int fila = tableListarTienda.rowAtPoint(evt.getPoint());
        txtIdCotizacion.setText(tableListarTienda.getValueAt(fila, 0).toString());
        txtNombreTienda.setText(tableListarTienda.getValueAt(fila, 1).toString());
        txtDireccionTienda.setText(tableListarTienda.getValueAt(fila, 2).toString());
        txtTelefonoTienda.setText(tableListarTienda.getValueAt(fila, 3).toString());
        txtUrlTienda.setText(tableListarTienda.getValueAt(fila, 4).toString());
        txtDistribucionTienda.setText(tableListarTienda.getValueAt(fila, 5).toString());

     
    }//GEN-LAST:event_tableListarTiendaMouseClicked

    private void btnEliminarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTiendaActionPerformed
        
        if(!"".equals(txtIdCotizacion.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar?");
            if(pregunta == 0){
                int id = Integer.parseInt(txtIdCotizacion.getText());
                nc.EliminarCotizacion(id);
                LimpiarCotizacion();
                ListarCotizacion();
                
            }
        }
    }//GEN-LAST:event_btnEliminarTiendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.gc();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTiendaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTienda;
    private javax.swing.JButton btnEliminarTienda;
    private javax.swing.JButton btnModificarTienda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableListarTienda;
    private javax.swing.JTextField txtDireccionTienda;
    private javax.swing.JTextField txtDistribucionTienda;
    private javax.swing.JTextField txtIdCotizacion;
    private javax.swing.JTextField txtNombreTienda;
    private javax.swing.JTextField txtTelefonoTienda;
    private javax.swing.JTextField txtUrlTienda;
    // End of variables declaration//GEN-END:variables
}

